### ISSUE TITLE
How to use this in Godot?

### ISSUE THREAD

**Issue by PeterGriffinDX2000** [uralys/godot-android-notifications#2]
I dont really see an API anywhere, so I dont really know how to initialize a notification. Unless I missed it, could you post an API or instructions on how to use this in Godot? This is my first time on Github, so I dont know the proper format of issue posts.

**Comment by PeterGriffinDX2000** [comment]
Nevermind, I just realised that the API is already in the code, leaving me only to add in a GD script to access those functions. Terribly sorry!

**Comment by chrisdugne** [comment]
1- build and install the plugin (should be the same as other godot plugins)

```
android/plugins
├── GodotAndroidNotifications.1.0.0.release.aar
├── GodotAndroidNotifications.gdap
```

2 - API

you have [2 functions](https://github.com/uralys/godot-android-notifications/blob/master/godot-android-notifications/src/main/java/org/godotengine/godot/plugin/androidnotifications/Scheduler.java#L111) available on godot side

## schedule

```gdscript
var notifier = Engine.get_singleton('GodotAndroidNotifications')
 
var notificationId = 'whatever, I use time stuff to get unique ids'

notifier.schedule(
  'the title',
  'the message',
  secsToNextNotification,
  notificationId
)
```

## cancel

You can store your `notificationId` anywhere, and use it to cancel the scheduling:

```
notifier.cancel(notificationId)
```
